resources:
- name: git-repo-test
  type: git
  source:
    branch: WIP-pipeline
    uri: https://github.com/harshild/learning-springboot.git

jobs:
- name: Unit Tests
  public: false
  plan:
    - get: git-repo-test
      trigger: true
      passed: [Deploy]
    - task: Run Tests
      file: git-repo-test/ci/task_run_tests.yml

- name: Deploy
  public: false
  plan:
    - get: git-repo-test
    - task: Deploy to CF
      file: git-repo-test/ci/task_deploy_cf.yml