resources:
- name: git-repo-test
  type: git
  source:
    branch: WIP-pipeline
    uri: https://github.com/harshild/learning-springboot.git

jobs:
- name: test-oss-pipeline
  public: false
  plan:
    - get: git-repo-test
      trigger: true
    - task: Run Tests
      file: git-repo-test/ci/task_run_tests.yml